### ISSUE TITLE
Error at matrix2meme step

### ISSUE THREAD

**Issue by sandertan** [slowkow/CENTIPEDE.tutorial#3]
Dear Kamil,

Thank you for making this tutorial. I'm trying to figure out how to use CENTIPEDE and your explanation about the steps are quite clear. I have a small issue with test example you give. When I execute the matrix2meme line you give in the tutorial, I run into the following error:

```
Can't use an undefined value as a HASH reference at
/home/sander/Programs/meme/lib/perl/MotifUtils.pm line 428, <STDIN> line 13.
```

Do you have any idea what I could have done wrong? I (think I) have installed meme correctly, including all it's (perl) dependencies. I've tried the version of meme you're using in the tutorial, and also the newest version. Running perl 5.18.2 from Ubuntu 14.04.

Kind regards,
Sander

Creygthon Lab, Hubrecht Institute

**Comment by slowkow** [comment]
Thanks for opening this issue! I'm very glad to hear that the explanations are clear.

I have not run into this problem myself, so it will be difficult to diagnose the problem.

Are you running the tutorial with all of the same files that I'm using? Or are you using some other set of files? One possible explanation is that the motif file you are using has some missing data that causes the perl program to crash with your error.

I might suggest skipping over the `matrix2meme` step in the tutorial and proceeding to the next steps. For example, you might already have a valid `.meme` file that you'd like to use instead of creating a new one from a position weight matrix.

**Comment by sandertan** [comment]
Thanks for the quick response! 

Yes I'm using the same files as you are. As you said, it's no problem because this is just for making the meme file.
